accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
   
        path('register/',views.register, name="register"),
        path('login/',views.login, name="login"),
        path('logout/',views.logout, name="logout"),
        path('dashboard/',views.dashboard, name="dashboard"),
        path('forgotPassword/',views.forgotPassword, name="forgotPassword"),
        path('',views.dashboard, name="dashboard"),
        
        path('activate/<uidb64>/<token>',views.activate, name="activate"),
        path('resetpassword_validate/<uidb64>/<token>',views.resetpassword_validate, name="resetpassword_validate"),
        path('resetPassword/',views.resetPassword, name="resetPassword"),
        path('edit_profile/',views.edit_profile, name="edit_profile"),
        path('change_password/',views.change_password, name="change_password"),
        path('coupon/',views.coupon_list, name="coupon"),
]

address/urls.py
from django.urls import path
from . import views

app_name = 'address'
urlpatterns = [
    path('address_list/', views.AddressListView.as_view(), name='address_list'),
    path('addresslist/', views.addresslist, name='addresslist'),
    path('create/', views.AddressCreateView.as_view(), name='address_create'),
    path('<int:pk>/', views.AddressUpdateView.as_view(), name='address_update'),
    path('<int:pk>/delete/', views.AddressDeleteView.as_view(), name='address_delete'),
]

carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.cart,name='cart'),
    path('wishlist',views.wishlist,name='wishlist'),
    path('add_to_cart/<int:product_id>/',views.add_to_cart,name='add_to_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/',views.remove_cart_item,name='remove_cart_item'),
    path('remove_cart_products/<int:product_id>/',views.remove_cart_products,name='remove_cart_products'),
    path('checkout',views.checkout,name="checkout"),
    
    
    path('add_to_wish/<int:product_id>/',views.add_to_wish,name='add_to_wish'),
    path('remove_wish_item/<int:product_id>/',views.remove_wish_item,name='remove_wish_item'),
    path('validate_coupon/',views.validate_coupon,name='validate_coupon'),
    path('apply_coupon/',views.apply_coupon,name='apply_coupon'),
    

   
   
   
]

greatkart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from . import views
# import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('store/',include('store.urls')),
    path('accounts/',include('accounts.urls')),
    path('category/', include('category.urls')),
    path('cart/',include('carts.urls')), 
    # path('categories/',views.categories,name='categories'),
    path('adminp/', include('adminp.urls')),
    path('orders/', include('orders.urls')),
    path('address/', include('address.urls')),
    path('adminpanel/', include('adminpanel.urls')),
    # path('__debug__/', include('debug_toolbar.urls')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "greatkart.views.page_not_found_view"

address/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render,redirect,HttpResponse,get_object_or_404
from .forms import RegistrationForm,UserForm,UserProfileForm 
from .models import Account,UserProfile
from carts.models import CartItem
# from carts.views import _cart_id
from django.contrib import messages,auth
from django.contrib.auth.decorators import login_required
import re
# Verification Email

from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode 
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator 
from django.core.mail import EmailMessage 
from orders.models import Order,Address
from adminp.models import Coupon,Wallet




def register(request):
    if request.method=='POST':
        form=RegistrationForm(request.POST)
        print(form)
        if form.is_valid():
            first_name=form.cleaned_data['first_name']
            last_name=form.cleaned_data['last_name']
            phone_number=form.cleaned_data['phone_number']
            email=form.cleaned_data['email']
            password=form.cleaned_data['password']
            username=email.split('@')[0]
            user=Account.objects.create_user(first_name=first_name,last_name=last_name,username=username,password=password,email=email)
            user.phone_number=phone_number
            user.save()
            # user activation
              # to get the domain of the current site  
            current_site = get_current_site(request)  
            mail_subject = 'Activation link has been sent to your email id'  
            #Check your email for further instruction, don't forget to check SPAM folder too.
            message = render_to_string('accounts/account_verification_email.html', {  
                'user': user,  
                'domain': current_site,  
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),  
                'token':default_token_generator.make_token(user),  
            }) 
            to_email = email 
            send_email=EmailMessage(  
                        mail_subject, message, to=[to_email]  
            )
            send_email.send()
            #messages.success(request,'Thank you for registering.We have sent you verification to your email.pls verify it')
            return redirect('/accounts/login/?command=verification&email='+email)
    else:      
        form=RegistrationForm
    context={
        'forms':form
    }
    return render (request,'accounts/register.html',context)

def login(request):
    if request.method=='POST':
        email =request.POST['email']
        password=request.POST['password']
        user=auth.authenticate(email=email,password=password)
        if user is not None:
            
            if user.is_admin:
                auth.login(request,user)
                return redirect('admin_dashboard')
            else: 
                auth.login(request,user)
                return redirect('home')
        else:
           messages.error(request,"Invalid login credentials")
           return redirect('login')
    return render (request,'accounts/login.html')

@login_required(login_url='login')
def logout(request):
    auth.logout(request)
    messages.success(request,"You are logged out.")
    return redirect('login')



def activate(request,uidb64, token):
    try:  
        # Encode the user's primary key as a base64 string
        uid = urlsafe_base64_decode(uidb64).decode() 
        user = Account._default_manager.get(pk=uid)  
    except(TypeError, ValueError, OverflowError,Account.DoesNotExist):  
        user = None  
        # Generate a token for a user also
    if user is not None and default_token_generator.check_token(user, token):  
        user.is_active = True  
        user.save()  
        messages.success(request,'Thank you for your email confirmation. Now you can login your account.')  
        
        
        # user profilr generation
        user_profile=UserProfile.objects.create(user=user)
        user_profile.save()
        
        #wallet with 0
        wallet=Wallet.objects.create(user=user)
        wallet.save()
        
        
        return redirect('login')
    else:  
        messages.error(request,'Invalid activation link')
        return redirect('register')
    
    
@login_required(login_url='login')    
def dashboard(request):
    orders=Order.objects.order_by("created_at").filter(user_id=request.user.id)
    order_count=orders.count()
   
    user=request.user
    userprofile=UserProfile.objects.get(user=user)
    context={
         'orders_count':order_count,
        'userprofile':userprofile,
    }
    return render(request,'accounts/dashboard.html',context)    



def forgotPassword(request):
    if request.method=="POST":
        email=request.POST['email']
        if Account.objects.filter(email=email).exists():
            user=Account.objects.get(email__exact=email)  
           #reset password email
            current_site = get_current_site(request)  
            mail_subject = 'Reset your password'  
            message = render_to_string('accounts/reset_password_email.html', {  
                'user': user,  
                'domain': current_site,  
                # Encode the user's primary key as a base64 string
                'uid':urlsafe_base64_encode(force_bytes(user.pk)), 
                 # Generate a token for a user also 
                'token':default_token_generator.make_token(user),  
            }) 
            to_email = email 
            send_email=EmailMessage(  
                        mail_subject, message, to=[to_email]  
            )
            send_email.send()
            
            messages.success(request,"Password reset email has been sent to your email")
            #Check your email for further instruction, don't forget to check SPAM folder too.
            return redirect('login')
        else:
            messages.error(request,'Account does not exists')   
            return redirect('forgotPassword') 
    return render(request,'accounts/forgotPassword.html')


def resetpassword_validate(request,uidb64, token):
    try:  
        uid = urlsafe_base64_decode(uidb64).decode() 
        user = Account._default_manager.get(pk=uid)  
    except(TypeError, ValueError, OverflowError,Account.DoesNotExist):  
        user = None  
    if user is not None and default_token_generator.check_token(user, token): 
        request.session['uid']=uid 
        messages.success(request,"  Please reset ur password")
        return redirect('resetPassword')
    else:
        messages.error(request,"This link has been expired")
        return redirect('login')
    

def resetPassword(request):
    if request.method=="POST":
        password=request.POST['password']
        confirm_password=request.POST['confirm_password']
        if password == confirm_password:
            
            
            if (len(password) < 8 or
               
                not re.search("[A-Z]", password) or
                not re.search("[0-9]", password) ):
                messages.error(request, "Please enter a strong password (minimum 8 characters, atleast one uppercase letter and one digit).")
                return redirect('resetPassword')
            else:
                uid = request.session.get('uid')
                user = Account.objects.get(pk=uid)
                user.set_password(password)
                user.save()
                messages.success(request, "Password reset successful.")
                return redirect('login')
        else:     
          messages.error(request,"Password not match")  
          return redirect('resetPassword')
    else:  
     return render (request,'accounts/resetPassword.html')
 
@login_required(login_url='login')
def edit_profile(request):
    userprofile=get_object_or_404(UserProfile,user=request.user)
    if request.method=='POST':
        user_form=UserForm(request.POST,instance=request.user)
        profile_form=UserProfileForm(request.POST,request.FILES,instance=userprofile)

        print(profile_form)
        if user_form.is_valid()and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request,'Your profile has been updated')
            return redirect('edit_profile')
    else:
            user_form=UserForm(instance=request.user)
            profile_form=UserProfileForm(instance=userprofile)
            
    context={
            'user_form':user_form,
            'profile_form':profile_form,
            'userprofile':userprofile, 
        }    
            
    return render(request,'accounts/edit_profile.html',context)

def addresses(request):
    address=Address.objects.filter(user=request.user).order_by('-created_at')
    context ={
        'address':address
    }
    return render(request,'accounts/address.html',context)


@login_required(login_url='login')
def change_password(request):
    if request.method=='POST':
        current_password=request.POST["current_password"]
        new_password=request.POST["new_password"]
        confirm_password=request.POST["confirm_password"]
        user=Account.objects.get(username__exact=request.user.username)
        if new_password==confirm_password:
            #check password in built function -stored in hashed format
            success=user.check_password(current_password)
            if success:
                user.set_password(new_password)
                user.save()
                auth.logout(request)
                messages.success(request,"Password updated successfully")
                
            messages.error(request,"Please enter valid current password")
            return redirect('change_password')
        else:
            messages.error(request,"Password does not match")
            return redirect('change_password')

address/views.py
from django.forms import TextInput
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from orders.models import Address
#from .models import Wallet

app_name = 'address'

class AddressListView(ListView):
    model = Address
    template_name = 'accounts/address_list.html'
    context_object_name = 'addresses'
    paginate_by = 10
    
def addresslist(request):
    address=Address.objects.filter(user=request.user)
    context={
        'addresses':address,
    }
    return render(request,'accounts/address_list.html',context)

class AddressCreateView(CreateView):
    model = Address
    fields = ['first_name', 'last_name', 'phone', 'address_line_1', 'address_line_2', 'city', 'state', 'country', 'zip_code']
    template_name = 'address_form.html'
    success_url = reverse_lazy('address:address_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class AddressUpdateView(UpdateView):
    model = Address
    fields = ['first_name', 'last_name', 'phone', 'address_line_1', 'address_line_2', 'city', 'state', 'country', 'zip_code']
    
    template_name = 'accounts/address_form.html'
    success_url = reverse_lazy('address:address_list')
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['first_name'].widget = TextInput(attrs={'placeholder': 'Enter your first name', "class": "form-control", 'label': False})
        form.fields['last_name'].widget = TextInput(attrs={'placeholder': 'Enter your last name', "class": "form-control", 'label': False})
        form.fields['phone'].widget = TextInput(attrs={'placeholder': 'Enter your phone number', 'label': False})
        form.fields['address_line_1'].widget = TextInput(attrs={'placeholder': 'Enter your address line 1', 'label': False})
        form.fields['address_line_2'].widget = TextInput(attrs={'placeholder': 'Enter your address line 2', 'label': False})
        form.fields['city'].widget = TextInput(attrs={'placeholder': 'Enter your city', 'label': False})
        form.fields['state'].widget = TextInput(attrs={'placeholder': 'Enter your state', 'label': False})
        form.fields['country'].widget = TextInput(attrs={'placeholder': 'Enter your country', 'label': False})
        form.fields['zip_code'].widget = TextInput(attrs={'placeholder': 'Enter your zip code', 'label': False})
        return form

class AddressDeleteView(DeleteView):
    model = Address
    template_name = 'address_confirm_delete.html'
    success_url = reverse_lazy('address:address_list')
    
    

templates/accounts/account_verification_email.html
{% autoescape off %}  
Hi {{ user.first_name }},  Thank you for signing up!
To confirm your email address and activate your account, click the link below.👇

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}  
If you encountered any issues while confirming the email, do not hesitate to Contact me.
{% endautoescape %}  

templates/accounts/address.html
{% extends 'base.html' %} {% load static%} {% block content %}

<section class="section-conten padding-y bg" style="margin-top: 100px">
  <div class="container card mb-5" style="background-color: white">
    <div class="row">
      {% include 'include/dashboard_sidebar.html' %}

      <main class="col-md-9">
        {% for message in messages %}
        <div>
          <p class=" my-5 alert alert-{{message.tags}}">{{message}}</p>
        </div>
        {% endfor %}

        <article class="card my-4">
          
          {%if orders%}
          <header class="card-header" style="background-color: #ffffff">
            <h3><strong class="d-inline-block mr-3">My orders</strong></h3>
          </header>
          <div class="card">
            <div class="card-body">
              <table class="table table-borderless">
                <thead class="text-muted">
                  <tr class="small text-uppercase">
                    <th scope="col">First-Name</th>
                    <th scope="col"></th>
                    <th scope="col">Total Price</th>
                    <th scope="col">Status</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>

                <tbody>
                  {% for item in orders %}
                  <tr>
                    <td>{{ item.created_at }}</td>
                    <td>{{ item.tracking_no }}</td>
                    <td>₹ {{ item.total_price }}</td>
                    {% if item.status == 'Cancelled' %}
                    <td class="text-danger"><b>{{ item.status }}</b></td>
                    {% elif item.status == 'Pending' %}
                    <td class="text-warning"><b>{{ item.status }}</b></td>
                    {% else %}
                    <td class="text-success fw-bold">
                      <b>{{ item.status }}</b>
                    </td>
                    {% endif %}

                    <td>
                      <a
                        href="{% url 'vieworder' item.tracking_no %}"
                        class="btn btn-dark"
                        >View</a
                      >
                    </td>
                  </tr>

                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
          {%else%}
          <div>
            <h2 class="text-center">Your order history is empty</h2>
            <div class="text-center">
              <a class="btn_1" href="{%url 'store'%}">Continue shopping..</a>
            </div>
          </div>
          {%endif%}
        </article>
        <!-- order-group.// -->
      </main>
    </div>
    <!-- row.// -->
  </div>
</section>

{% endblock %}

templates/accounts/address_form.html
{% extends 'base.html' %} {% block content %}
<section class="section-conten padding-y bg" style="margin-top: 100px">
  <div class="container card mb-5" style="background-color: white">
    <div class="row">
      {%include 'include/dashboard_sidebar.html'%}
      <main class="col-md-9">
        <h1>
          {% if request.resolver_match.url_name == 'address_create' %}Add{% else
          %}Update{% endif %} Address
        </h1>
        <form
          method="post"
          style="padding: 20px; margin: 20px"
          class="form-group"
        >
          {% csrf_token %} {{ form.as_p }}
          <input type="submit" value="Save" />
        </form>
      </main>
    </div>
  </div>
</section>
{% endblock %}

templates/accounts/address_list.html
{% extends 'base.html' %} {% block content %}


<section class="section-conten padding-y bg" style="margin-top: 100px">
    <div class="container card mb-5" style="background-color: white">
      <div class="row">
        {% include 'include/dashboard_sidebar.html' %}
  
        <main class="col-md-9">
          {% for message in messages %}
          <div>
            <p class=" my-5 alert alert-{{message.tags}}">{{message}}</p>
          </div>
          {% endfor %}
  
          <article class="card my-3">
            <header class="card-header" style="background-color: #ffffff">
              <h3><strong class="d-inline-block mr-3">Address </strong></h3>
            </header>
            <div class="card-body d-flex flex-wrap justify-content-between"> <!-- add the flexbox classes -->
              {% for address in addresses %}
              <div class="card mx-3 my-3" style="width: 18rem;"> <!-- add the margin classes -->
                <div class="card-body">
                  <h5 class="card-title">{{ address.first_name }} {{ address.last_name }} </h5>
                  <p class="card-text"><h6>{{address.address_line_1}} {{ address.address_line_2|default:'' }} -</h6></p>
                  <h6 class="card-subtitle mb-2 text-muted"> {{address.city }},<br> {{ address.state }},<br> {{ address.country }} -<br>
                    {{address.zip_code }}</h6>
                  <a href="{% url 'address:address_update' address.pk %}" class="card-link">Edit</a>
                  <a href="{% url 'address:address_delete' address.pk %}" class="card-link">Delete</a>
                </div>
              </div>
              {% endfor %}
            
            </div>
  
          </article>
          <!-- order-group.// -->
        </main>
  
        <!-- row.// -->
      </div>
    </div>
  </section>
  
{% endblock %}

templates/accounts/coupon_list.html
{% extends 'base.html' %} {% load static%} {% block content %}

<section class="section-conten padding-y bg" style="margin-top: 100px">
  <div class="container card mb-5" style="background-color: white">
    <div class="row">
      {% include 'include/dashboard_sidebar.html' %}

      <main class="col-md-9">
        {% for message in messages %}
        <div>
          <p class=" my-5 alert alert-{{message.tags}}">{{message}}</p>
        </div>
        {% endfor %}

        <article class="card my-4">
          {%if coupons%}
          <header class="card-header" style="background-color: #ffffff">
            <h3><strong class="d-inline-block mr-3">Coupon List</strong></h3>
          </header>
          <div class="card">
            <div class="card-body">
            

              <ul>
                <table class="table table-borderless">
                  {% for coupon in coupons %}
                 <a href="{%url 'store'%}"><li>
                    <b>{{ coupon.coupon_code }}</b> -
                    {{coupon.discount_percentage }}% off - Expires on
                    {{coupon.expiry_date|date:'F j, Y' }} - Minimum purchase
                    amount: ${{ coupon.minimum_purchase_amount }}</a> 
                  </li>
                  <hr />
                </table>
                {% endfor %}
              </ul>
            </div>
          </div>
          {%else%}
          <div>
            <h2 class="text-center">Coupon list is empty</h2>
            <div class="text-center">
              <a class="btn_1" href="{%url 'store'%}">Continue shopping..</a>
            </div>
          </div>
          {%endif%}
        </article>
        <!-- order-group.// -->
      </main>
    </div>
    <!-- row.// -->
  </div>
</section>

{% endblock %}

templates/accounts/edit_profile.html
{% extends 'base.html' %} {% load static%} {% block content %}

<section class="section-conten padding-y bg" style="margin-top: 100px">
  <div class="container card mb-5" style="background-color: white">
    <div class="row">
      {%include 'include/dashboard_sidebar.html'%}

      <main class="col-md-9">
        {% for message in messages %}
        <div>
          <p class=" my-5 alert alert-{{message.tags}}">{{message}}</p>
        </div>
        {% endfor %}
        <article class="card my-4">
          <header class="card-header">
            <strong class="d-inline-block mr-3"> Edit Profile </strong>
            <span>{{user.full_name}}</span>
          </header>
          <div class="card-body">
            {% if userprofile.profile_picture %}
            <div class="text-right">
              <img
                src="{{userprofile.profile_picture.url}}"
                alt="Profile
              Picture"
                width="100"
                style="border-radius: 50px"
              />
            </div>
            {% endif %}
            <div class="row">
              <div class="col-md-12">
                <form
                  action="{% url 'edit_profile' %}"
                  method="POST"
                  enctype="multipart/form-data"
                >
                  {% csrf_token %}
                  <div class="form-row">
                    <div class="col-md-6">
                      <div class="form-group">
                        {% comment %} <label>First Name</label> {% endcomment %}
                        {{ user_form.first_name}}
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        {% comment %} <label>Last Name</label> {% endcomment %}
                        {{user_form.last_name}}
                      </div>
                    </div>
                  </div>
                  <div class="form-row">
                    <div class="form-group col-md-6">
                      {% comment %} <label>Phone Number</label> {% endcomment %}
                      {{ user_form.phone_number}}
                    </div>
                    <div class="form-group col-md-6">
                      {% comment %} <label>Profile Picture</label>
                      {%endcomment%} {{ profile_form.profile_picture}}
                    </div>
                  </div>
                  <div class="form-group">
                    {% comment %} <label>Address line 1</label> {% endcomment %}
                    {{ profile_form.address_line_1}}
                  </div>
                  <div class="form-group">
                    {% comment %} <label>Address line 2</label> {% endcomment %}
                    {{ profile_form.address_line_2}}
                  </div>
                  <div class="form-row">
                    <div class="form-group col-md-3">
                      {% comment %} <label>City</label> {% endcomment %}
                      {{profile_form.city}}
                    </div>
                    <div class="form-group col-md-3">
                      {% comment %} <label>State</label> {% endcomment %}
                      {{profile_form.state}}
                    </div>
                    <div class="form-group col-md-3">
                      {% comment %} <label>Country</label> {% endcomment %}
                      {{profile_form.country}}
                    </div>
                    <div class="form-group col-md-3">
                      {% comment %} <label>Country</label> {% endcomment %}
                      {{profile_form.zip_code}}
                    </div>
                  </div>
                  <input type="submit" value="Save" class="btn-info" />
                </form>
              </div>
            </div>
            <!-- row.// -->
          </div>
        </article>
      </main>
    </div>
  </div>
</section>
{% endblock %}

templates/accounts/forgotPassword.html
{% extends 'base.html' %}
{%block content%}    
    <section class="login_part padding_top">
    <div class="container">
    <div class="row align-items-center">
    <div class="col-lg-6 col-md-6">
    <div class="login_part_text text-center">
        <div class="login_part_text_iner">
            <h2>New to our Shop?</h2>
            <p>There are advances being made in science and technology
            everyday, and a good example of this is the</p>
            <a href="{%url 'register'%}" class="btn_3">Create an Account</a>
            </div>
    </div>
    </div>
    <div class="col-lg-6 col-md-6">
    <div class="login_part_form">
    <div class="login_part_form_iner">
    <h3>Forgot Password?</h3>
    <form class="row contact_form" action="{%url 'forgotPassword'%}" method="POST" novalidate="novalidate">
    {% csrf_token%}
    {%include 'include/alert.html'%}
        <div class="col-md-12 form-group p_star">
    <input type="email" class="form-control"  name="email" value="" placeholder="Email Address">
    </div>
    <div class="col-md-12 form-group p_star">
        <a class="lost_pass" href="{%url 'login'%}">Got password? Login</a>
    </div>
    <div class="col-md-12 form-group">
    
    <button type="submit" value="submit" class="btn_3">
    Submit
    </button>
   
    </div>
    </form>
    </div>
    </div>
    </div>
    </div>
    </div>
    </section>

{%endblock%}

templates/accounts/resetPassword.html
{% extends 'base.html' %} {%block content%}

<section class="login_part padding_top">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 col-md-6">
        <div class="login_part_text text-center">
          <div class="login_part_text_iner">
            <h2>Reset Password</h2>
            <p>
              There are advances being made in science and technology everyday,
              and a good example of this is the
            </p>
            <a href="{%url 'register'%}" class="btn_3">Create an Account</a>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-6">
        <div class="login_part_form">
          <div class="login_part_form_iner">
            <h3>
              Welcome Back ! <br />
              Reset Password
            </h3>
            <form
              class="row contact_form"
              action="{%url 'resetPassword'%}"
              method="POST"
            >
              {% csrf_token%} {%include 'include/alert.html'%}
              <div class="col-md-12 form-group p_star">
                <input
                  type="password"
                  class="form-control"
                  name="password"
                  value=""
                  placeholder="Create Password"
                  required
                />
              </div>
              <div class="col-md-12 form-group p_star">
                <input
                  type="password"
                  class="form-control"
                  id="confirm_password"
                  name="confirm_password"
                  value=""
                  placeholder="Confirm Password"
                  required
                />
              </div>
              <div class="col-md-12 form-group">
                <div class="creat_account d-flex align-items-center">
                  <input type="checkbox" id="f-option" name="selector" />
                  <label for="f-option">Remember me</label>
                </div>
                <button type="submit" value="submit" class="btn_3">
                  Reset
                </button>
                <a class="lost_pass" href="{%url 'forgotPassword'%}"
                  >forget password?</a
                >
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

  {%endblock%}
</section>

templates/accounts/reset_password_email.html
{% autoescape off %}  
Hi {{ user.first_name }},  
As requested ,please click below link to reset your password 
http://{{ domain }}{% url 'resetpassword_validate' uidb64=uid token=token %}  
If you think it's not you ,please ignore this email
{% endautoescape %} 