adminp/urls.py
from django.urls import path
from . import views
app_name = 'coupons'
urlpatterns = [
   
    path('wallet_balance',views.wallet_balance, name="wallet_balance"),
    
    path('coupon_list', views.coupon_list, name='coupon_list'),
    path('coupon_create/', views.coupon_create, name='coupon_create'),
    path('<int:pk>/', views.coupon_detail, name='detail'),
    path('<int:pk>/update/', views.coupon_update, name='update'),
    path('<int:pk>/delete/', views.coupon_delete, name='delete'),
]

carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.cart,name='cart'),
    path('wishlist',views.wishlist,name='wishlist'),
    path('add_to_cart/<int:product_id>/',views.add_to_cart,name='add_to_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/',views.remove_cart_item,name='remove_cart_item'),
    path('remove_cart_products/<int:product_id>/',views.remove_cart_products,name='remove_cart_products'),
    path('checkout',views.checkout,name="checkout"),
    
    
    path('add_to_wish/<int:product_id>/',views.add_to_wish,name='add_to_wish'),
    path('remove_wish_item/<int:product_id>/',views.remove_wish_item,name='remove_wish_item'),
    path('validate_coupon/',views.validate_coupon,name='validate_coupon'),
    path('apply_coupon/',views.apply_coupon,name='apply_coupon'),
    

   
   
   
]

greatkart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from . import views
# import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('store/',include('store.urls')),
    path('accounts/',include('accounts.urls')),
    path('category/', include('category.urls')),
    path('cart/',include('carts.urls')), 
    # path('categories/',views.categories,name='categories'),
    path('adminp/', include('adminp.urls')),
    path('orders/', include('orders.urls')),
    path('address/', include('address.urls')),
    path('adminpanel/', include('adminpanel.urls')),
    # path('__debug__/', include('debug_toolbar.urls')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "greatkart.views.page_not_found_view"

store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse
from django.utils.text import slugify

class Product(models.Model):
    product_name=models.CharField(max_length=200,unique=True)
    slug=models.SlugField(max_length=200,unique=True)
    description=models.TextField(max_length=500,blank=True)
    price=models.IntegerField()
    images=models.ImageField(upload_to='photos/products')
    stock=models.IntegerField()
    is_available=models.BooleanField(default=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    created_date=models.DateTimeField(auto_now_add=True)
    modified_date=models.DateTimeField(auto_now_add=True)
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.product_name)
        super().save(*args, **kwargs)
        
    
    
    def get_url(self):
        return reverse('product_detail',args=[self.category.slug,self.slug])
    
    
    def __str__(self):
        return self.product_name
    
    
    
    

templates/manager/add_category.html
{% extends 'admin/admin_base.html' %} {% block content %}
<section class="section-content padding-y bg">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-12">
        <h1 class="text-center h2 mb-4">Add Category</h1>
        <form
          action="{% url 'add_category' %}"
          method="POST"
          enctype="multipart/form-data"
        >
          {% csrf_token %}
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="id_name">Category Name</label>
              {{ form.category_name }}
            </div>
            {% comment %}
            <div class="form-group col-md-6">
              <label for="category_slug">Category Slug</label>
              {{ form.slug }}
            </div>
            {% endcomment %}
            <div class="form-group col-md-6"></div>
            <div class="form-group col-md-6">
              <label for="description">Description</label>
              {{ form.description }}
            </div>
            <div class="form-group col-md-6">
              <label for="image">Image</label>
              {{ form.cat_image }}
            </div>
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-dark">
              Save <i class="fa fa-bookmark" aria-hidden="true"></i>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/manager/add_product.html
{% extends 'admin/admin_base.html' %} {% load static%} {% block content %}

<section class="section-content padding-y bg" style="margin-top: 100px">
  <div class="container mt-5 mb-5">
    <div class="row d-flex justify-content-center">
      <div class="col-8">
        {% for message in messages %}
        <div>
          <p class=" my-5 alert alert-{{message.tags}}">{{message}}</p>
        </div>
        {% endfor %}
        <h2 class="text-center font-weight-bold my-5">Add Products</h2>

        <form
          action="{% url 'add_product' %}"
          method="POST"
          enctype="multipart/form-data"
        >
          {% csrf_token %}
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="id_name">Product Name</label>
              {{ form.product_name }}
            </div>

            <div class="form-group col-md-6">
              <label for="product_price">Product Price</label>
              {{ form.price }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_image">Product Image</label>
              {{ form.images }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_stock">Product Stock</label>
              {{ form.stock }}
            </div>

            <div class="form-group col-md-6">
              <label for="product_category">Category</label>
              {{ form.category }}
            </div>
            <div class="form-group col-md-6">
              <label for="id_is_available">Available</label>
              {{ form.is_available }}
            </div>
          </div>

          <div class="form-group">
            <label for="product_description">Product Description</label>
            {{ form.description }}
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-dark">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/manager/admin_change_password.html
{% extends 'admin/admin_base.html' %} {% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y bg">
  <div class="container">
    <h1 class="text-center h2 mb-4">Change Password</h1>
    <div class="row">
      <main class="col-md-9">
        {% if messages %} {% for message in messages %}
        {% if message.tags == 'success' %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% elif message.tags == 'error' %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% else %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endif %}
        {% endfor %} {% endif %}
        <form action='{% url 'admin_change_password' %}' method='POST'>
          {% csrf_token %}
          <div class="form-group">
            <label for="current_password">Current Password</label>
            <input type="password" class="form-control" id="current_password" name="current_password" placeholder="Enter current password" />
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter new password" />
          </div>
          <div class="form-group">
            <label for="confirm_password">Retype Password</label>
            <input type="password" class="form-control" id="confirm_password" name="confirm_password" placeholder="Enter confirm password" />
          </div>
          <button type="submit" class="btn btn-dark">Submit</button>
        </form>
      </main>
    </div>
    <!-- row.// -->
  </div>
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}

templates/manager/category_management.html
{% extends 'admin/admin_base.html' %} {% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<style>
  .swal-modal {
    width: 400px;
  }

  .swal-title {
    font-size: 18px;
  }

  .swal-text {
    font-size: 14px;
  }
</style>
<section class="section-content mt-3 bg">
  <div class="container">
    <h1 class="text-center h2 mb-4">Manage Categories</h1>
    <div class="d-flex mb-3 justify-content-end">
      <form action="{% url 'manage_category' %}" class="search" method="POST">
        {% csrf_token %}
        <div class="input-group w-100">
          <input
            type="text"
            class="form-control"
            style="width: 60%"
            placeholder="Search"
            name="keyword"
          />

          <div class="input-group-append">
            <button class="btn btn-dark" type="submit">
              <i class="fa fa-search"></i>
            </button>
          </div>
        </div>
      </form>
    </div>
    <div class="row">
      <main class="col-md-9">
        <div class="d-flex justify-content-end">
          <a href="{% url 'add_category' %}" class="btn btn-info mr-md-0"
            >Add <i class="fa fa-plus-circle" aria-hidden="true"></i
          ></a>
        </div>
        <table class="table table-borderless">
          <thead>
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Category Name</th>
              <th scope="col">Category Slug</th>
              <th scoop="col">Description</th>
              <th scope="col">Delete</th>
            </tr>
          </thead>
          <tbody>
            {% for category in categories %}
            <tr>
              <th scope="row">{{ category.id }}</th>
              <td>{{ category.category_name }}</td>
              <td>{{ category.description }}</td>
              <td>{{ category.slug }}</td>
              <td>
                {% comment %}
                <a
                  href="{% url 'delete_category' category.id %}"
                  class="btn btn-sm btn-danger"
                  >Delete <i class="fa fa-trash" aria-hidden="true"></i
                ></a>
                {% endcomment %}

                <form
                  method="POST"
                  action="{% url 'delete_category' category.id %}"
                >
                  {% csrf_token %}
                  <input name="_method" type="hidden" value="DELETE" />
                  <button
                    type="submit"
                    class="btn btn-sm btn-danger show_confirm"
                    data-toggle="tooltip"
                    title="Delete"
                  >
                    Delete<i class="fa fa-trash" aria-hidden="true"></i>
                  </button>
                </form>
              </td>
              <td>
                <a
                  href="{% url 'edit_category' category.id %}"
                  class="btn btn-sm btn-secondary"
                  >Edit <i class="fa fa-wrench" aria-hidden="true"></i
                ></a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <!-- order-group.// -->
      </main>
    </div>
    <!-- row.// -->
  </div>
  <div class="container">
    <div class="row">
      <aside class="col-md-3"></aside>
      <main class="col-md-9">
        <nav class="mt-4" aria-label="Page navigation sample">
          {% if categories.has_other_pages %}
          <ul class="pagination">
            {% if categories.has_previous %}
            <li class="page-item">
              <a
                class="page-link"
                href="?page={{ categories.previous_page_number }}"
                >Previous</a
              >
            </li>
            {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#">Previous</a>
            </li>
            {% endif %} {% for page_number in categories.paginator.page_range %}
            {% if categories.number == page_number %}
            <li class="page-item active">
              <a class="page-link" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_number }}"
                >{{ page_number }}</a
              >
            </li>
            {% endif %} {% endfor %} {% if categories.has_next %}
            <li class="page-item">
              <a
                class="page-link"
                href="?page={{ categories.next_page_number }}"
                >Next</a
              >
            </li>
            {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#">Next</a>
            </li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
      </main>
    </div>
  </div>
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
<script type="text/javascript">
  $(".show_confirm").click(function (event) {
    var form = $(this).closest("form");
    var name = $(this).data("name");
    event.preventDefault();
    swal({
      title: `Are you sure you want to delete this coupon?`,

      icon: "warning",
      buttons: true,
      dangerMode: true,
    }).then((willDelete) => {
      if (willDelete) {
        form.submit();
      }
    });
  });
</script>
{% endblock content %}

templates/manager/coupon_confirm_delete.html
{% extends 'admin/admin_base.html' %} {% block content %}
<h2>Confirm Delete</h2>
<p>Are you sure you want to delete the coupon "{{ coupon.coupon_code }}"?</p>
<form method="post">
  {% csrf_token %}
  <button type="submit">Delete</button>
  <a href="{% url 'coupons:list' %}">Cancel</a>
</form>
{% endblock %}

templates/manager/coupon_form.html
{% extends 'admin/admin_base.html' %} {% block content %}
{% comment %} <h2>{% if form.instance.pk %}Update{% else %}Create{% endif %} Coupon</h2>
<form method="post">
  {% csrf_token %}   
   <div class="form-group">
    {{ form.as_p }}
  </div>
  <button type="submit"class="btn btn-primary">Save</button>
</form> {% endcomment %}
<style>
  .form-group label {
      display: block;
      margin-bottom: 10px;
      font-weight: bold;
  }
  .form-group input[type=text], 
  .form-group input[type=date], 
  .form-group input[type=number] {
      width: 40%;
      padding: 10px;
      font-size: 16px;
      border-radius: 5px;
      border: 1px solid #ccc;
      margin-bottom: 20px;
  }
  .form-group input[type=submit] {
      background-color: #007bff;
      color: #fff;
      padding: 10px 20px;
      font-size: 16px;
      border-radius: 5px;
      border: none;
      cursor: pointer;
  }
</style>
<h2>{% if form.instance.pk %}Update{% else %}Create{% endif %} Coupon</h2>
<form method="post">
    {% csrf_token %}   
    <div class="form-group">
        <label for="{{ form.coupon_code.id_for_label }}">Coupon Code</label>
        {{ form.coupon_code }}
    </div>
    <div class="form-group">
        <label for="{{ form.discount_percentage.id_for_label }}">Discount Percentage</label>
        {{ form.discount_percentage }}
    </div>
    <div class="form-group">
        <label for="{{ form.expiry_date.id_for_label }}">Expiry Date</label>
        {{ form.expiry_date }}
    </div>
    <div class="form-group">
        <label for="{{ form.minimum_purchase_amount.id_for_label }}">Minimum Purchase Amount</label>
        {{ form.minimum_purchase_amount }}
    </div>
    <input type="submit"class="btn btn-primary" value="Save">
</form>
{% endblock %}

templates/manager/coupon_list.html
{% extends 'admin/admin_base.html' %} {% block content %}
<h2>Coupon List</h2>
<table class="table">
  <thead>
    <tr>
      <th>Sl No</th>
      <th>Coupon Code</th>
      <th>Discount Percentage</th>
      <th>Expiry Date</th>
      <th>Minimum Purchase Amount</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for coupon in coupons %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td>{{ coupon.coupon_code }}</td>
      <td>{{ coupon.discount_percentage }}</td>
      <td>{{ coupon.expiry_date }}</td>
      <td>{{ coupon.minimum_purchase_amount }}</td>
      <td>
        {% comment %}
        <a href="{% url 'coupons:detail' coupon.pk %}">Detail</a>
        {% endcomment%}

        <a href="{% url 'coupons:update' coupon.pk %}">Update</a>
        <a href="{% url 'coupons:delete' coupon.pk %}">Delete</a>
      </td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="5">No coupons found.</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

templates/manager/edit_category.html
{% extends 'admin/admin_base.html' %} {% block content %}
<section class="section-content padding-y bg">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-12">
        <h1 class="text-center h2 mb-4">Edit Category</h1>
        <form
          action="{% url 'edit_category' category.id %}"
          method="POST"
          enctype="multipart/form-data"
        >
          {% csrf_token %}
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="id_name">Category Name</label>
              {{ form.category_name }}
            </div>
            {% comment %}
            <div class="form-group col-md-6">
              <label for="category_slug">Category Slug</label>
              {{ form.slug }}
            </div>
            {% endcomment %}
            <div class="form-group col-md-6"></div>
            <div class="form-group col-md-6">
              <label for="description">Description</label>
              {{ form.description }}
            </div>
            <div class="form-group col-md-6">
              <label for="image">Image</label>
              {{ form.cat_image }}
            </div>
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-dark">
              Save <i class="fa fa-bookmark" aria-hidden="true"></i>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/manager/edit_product.html
{% extends 'base.html' %} {% block content %}
<section class="section-content padding-y bg">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-8">
        <h1 class="text-center h2 mb-4">Edit Product</h1>
        <form
          action="{% url 'edit_product' product.id %}"
          method="POST"
          enctype="multipart/form-data"
        >
          {% csrf_token %}
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="id_name">Product Name</label>
              {{ form.product_name }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_slug">Product Slug</label>
              {{ form.slug }} {% comment %}
              <small id="product_slug" class="form-text text-muted"
                >Format :- name: ATX Jeans, slug: atx-jeans</small
              >
              {% endcomment %}
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="product_price">Product Price</label>
              {{ form.price }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_image">Product Image</label>
              {{ form.images }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_stock">Product Stock</label>
              {{ form.stock }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_category">Category</label>
              {{ form.category }}
            </div>
            <div class="form-group col-md-6">
              <label for="id_is_available">Available</label>
              {{ form.is_available }}
            </div>
          </div>

          <div class="form-group">
            <label for="product_description">Product Description</label>
            {{ form.description }}
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-dark">
              Save <i class="bi bi-sd-card-fill"></i>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/manager/manager_vieworder.html
{% extends 'admin/admin_base.html' %} {% load static%} {% block content %}

<div class="container my-3">
  <div class="row">
    <div class="col-md-12" style="margin-top: 70px">
      <div class="card shadow">
        <div class="card-header">
          <h3>View order</h3>
        </div>
        <div class="card-body">
          {% for message in messages %}
          <div>
            <p class=" my-5 alert alert-{{message.tags}}">{{message}}</p>
          </div>
          {% endfor %}
          <div class="row">
            <div class="col-md-6">
              <h4>Shipping Details</h4>
              <hr />
              <label class="mt-2"> Name</label>
              <div class="border p-1">
                {{order.first_name}} {{ order.last_name }}
              </div>

              <label class="mt-2">Email</label>
              <div class="border p-1">{{order.email}}</div>
              <label class="mt-2">Phone Number</label>
              <div class="border p-1">{{order.phone}}</div>
              <label class="mt-2">Delivery Address</label>
              <div class="border p-1">
                {{order.address_line_1}} <br />
                {{order.city}} <br />
                {{order.state}} <br />
                {{order.country}} <br />
                Pin Code : {{order.zip_code}}
              </div>
            </div>
            <div class="col-md-6">
              <h4>Order Details</h4>
              <table class="table table-borderless">
                <thead class="text-muted">
                  <tr class="small text-uppercase">
                    <th scope="col">Product</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Price</th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody>
                  {% for item in orderitems %}
                  <tr>
                    <td>
                      <figure class="itemside align-items-center">
                        <div class="how-itemcart1">
                          <img
                            src="{{ item.product.images.url }}"
                            style="height: 100px"
                            alt="IMG"
                          />
                        </div>
                        <figcaption class="info">
                          <a href="#" class="title text-dark"
                            >{{ item.product.product_name }}</a
                          >
                        </figcaption>
                      </figure>
                    </td>
                    <td class="column">
                      <label class="my-3" for="">{{ item.quantity }}</label>
                    </td>
                    <td>
                      <div class="price-wrap">
                        <var class="price">₹{{ item.price }}</var><br />
                        <small class="text-muted">
                          ₹{{ item.product.price}} each
                        </small>
                      </div>
                      <!-- price-wrap .// -->
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              <hr />
              <div>
                <h5 class="d-flex align-end">
                  Grand Total : ₹{{order.total_price}}
                </h5>
                <br />
                <h6>Payment Mode : {{order.payment_mode}}</h6>
                <br />
                {% if order.status == 'Cancelled' %}
                <h6>
                  Order Status:
                  <span class="text-danger">{{order.status}}</span>
                </h6>
                <br />
                {% elif order.status == 'Delivered' %}
                <h6>
                  Order Status:
                  <span class="text-success">{{order.status}}</span>
                </h6>
                <br />
                {% elif order.status == 'Pending' %}
                <h6>
                  Order Status:
                  <span class="text-warning">{{order.status}}</span>
                </h6>
                <br />
                {% elif order.status == 'Shipped' %}
                <h6>
                  Order Status:
                  <span class="text-primary">{{order.status}}</span>
                </h6>
                <br />
                {% elif order.status == 'Out For Shipping' %}
                <h6>
                  Order Status: <span class="text-info">{{order.status}}</span>
                </h6>
                <br />
                {% endif %}
                <h6>Tracking Number : {{order.tracking_no}}</h6>
                <br />
              </div>
              {% if order.status == 'Order Placed ' %}
              <div class="d-flex justify-content-end my-2">
                <a href="{% url 'manager_accept_order' order.tracking_no %}"
                  ><button class="btn btn-success">Accept Order</button></a
                >
              </div>

              {% elif order.status == 'Out For Shipping' %}
              <div class="d-flex justify-content-end my-2">
                <a href="{% url 'manager_ship_order' order.tracking_no %}"
                  ><button class="btn btn-primary">Shipped</button></a
                >
              </div>
              {% elif order.status == 'Shipped' %}
              <div class="d-flex justify-content-end my-2">
                <a href="{% url 'manager_delivered_order' order.tracking_no %}"
                  ><button class="btn btn-success">Delivered</button></a
                >
              </div>
              {% endif %} {% comment %} {% if order.status == 'Out For Shipping'
              or order.status == 'Shipped' %}

              <div class="d-flex justify-content-end my-2">
                <a href="{% url 'manager_cancel_order' order.tracking_no %}"
                  ><button class="btn btn-danger">Cancel Order</button></a
                >
              </div>
              {% endif %} {% endcomment %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}