address/urls.py
from django.urls import path
from . import views

app_name = 'address'
urlpatterns = [
    path('address_list/', views.AddressListView.as_view(), name='address_list'),
    path('addresslist/', views.addresslist, name='addresslist'),
    path('create/', views.AddressCreateView.as_view(), name='address_create'),
    path('<int:pk>/', views.AddressUpdateView.as_view(), name='address_update'),
    path('<int:pk>/delete/', views.AddressDeleteView.as_view(), name='address_delete'),
]

adminp/urls.py
from django.urls import path
from . import views
app_name = 'coupons'
urlpatterns = [
   
    path('wallet_balance',views.wallet_balance, name="wallet_balance"),
    
    path('coupon_list', views.coupon_list, name='coupon_list'),
    path('coupon_create/', views.coupon_create, name='coupon_create'),
    path('<int:pk>/', views.coupon_detail, name='detail'),
    path('<int:pk>/update/', views.coupon_update, name='update'),
    path('<int:pk>/delete/', views.coupon_delete, name='delete'),
]

carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.cart,name='cart'),
    path('wishlist',views.wishlist,name='wishlist'),
    path('add_to_cart/<int:product_id>/',views.add_to_cart,name='add_to_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/',views.remove_cart_item,name='remove_cart_item'),
    path('remove_cart_products/<int:product_id>/',views.remove_cart_products,name='remove_cart_products'),
    path('checkout',views.checkout,name="checkout"),
    
    
    path('add_to_wish/<int:product_id>/',views.add_to_wish,name='add_to_wish'),
    path('remove_wish_item/<int:product_id>/',views.remove_wish_item,name='remove_wish_item'),
    path('validate_coupon/',views.validate_coupon,name='validate_coupon'),
    path('apply_coupon/',views.apply_coupon,name='apply_coupon'),
    

   
   
   
]

greatkart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from . import views
# import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('store/',include('store.urls')),
    path('accounts/',include('accounts.urls')),
    path('category/', include('category.urls')),
    path('cart/',include('carts.urls')), 
    # path('categories/',views.categories,name='categories'),
    path('adminp/', include('adminp.urls')),
    path('orders/', include('orders.urls')),
    path('address/', include('address.urls')),
    path('adminpanel/', include('adminpanel.urls')),
    # path('__debug__/', include('debug_toolbar.urls')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "greatkart.views.page_not_found_view"

templates/include/alert.html
{% if messages %}

    {% for message in messages %}
    <div id="message" class="container">
    <div{% if message.tags %} class="alert alert-{{message.tags}}"{% endif %}role="alert">
     <button type="button" class="close" data-dismiss="alert"><span aria-hidden="True">&times;</span></button>    
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
        {{ message }}
    </div>
   

    


</div>
    {% endfor %}

{% endif %}

templates/include/dashboard_sidebar.html
<aside class="sidebar col-md-3">
  <div class="sidebar-layout pt:5rem">
    <div class="sidebar-content">
      <ul class="list-group">
        <a href="{%url 'dashboard'%}" class="list-group-item">Dashboard</a>

        <a href="{%url 'myorder'%}" class="list-group-item">My orders </a>

        <a href="{%url 'edit_profile'%}" class="list-group-item"
          >Edit Profile
        </a>
        <a href="{%url 'address:addresslist'%}" class="list-group-item"
          >Manage Addresses</a
        >

        <a href="{%url 'coupon'%}" class="list-group-item">My Coupons</a>

        {% comment %} <a href="{%url 'coupons:wallet_balance'%}" class="list-group-item"
          >My Wallet</a
        > {% endcomment %}

        <a href="{%url 'change_password'%}" class="list-group-item"
          >Change Password</a
        >

        <br />

        <a
          href="{%url 'logout'%}"
          class="btn btn-primary btn-lg active"
          role="button"
          aria-pressed="true"
          >Logout</a
        >
      </ul>
    </div>
  </div>
</aside>

templates/include/footer.html
{%load static%}
<footer class="footer_part">
    <div class="container">
    <div class="row justify-content-around">
    <div class="col-sm-6 col-lg-2">
    <div class="single_footer_part">
    <h4>Top Products</h4>
    <ul class="list-unstyled">
    <li><a href="#">Managed Website</a></li>
    <li><a href="#">Manage Reputation</a></li>
    <li><a href="#">Power Tools</a></li>
    <li><a href="#">Marketing Service</a></li>
    </ul>
    </div>
    </div>
    <div class="col-sm-6 col-lg-2">
    <div class="single_footer_part">
    <h4>Quick Links</h4>
    <ul class="list-unstyled">
    <li><a href="#">Jobs</a></li>
    <li><a href="#">Brand Assets</a></li>
    <li><a href="#">Investor Relations</a></li>
    <li><a href="#">Terms of Service</a></li>
    </ul>
    </div>
    </div>
    <div class="col-sm-6 col-lg-2">
    <div class="single_footer_part">
    <h4>Features</h4>
    <ul class="list-unstyled">
    <li><a href="#">Jobs</a></li>
    <li><a href="#">Brand Assets</a></li>
    <li><a href="#">Investor Relations</a></li>
    <li><a href="#">Terms of Service</a></li>
    </ul>
    </div>
    </div>
    <div class="col-sm-6 col-lg-2">
    <div class="single_footer_part">
    <h4>Resources</h4>
    <ul class="list-unstyled">
    <li><a href="#">Guides</a></li>
    <li><a href="#">Research</a></li>
    <li><a href="#">Experts</a></li>
    <li><a href="#">Agencies</a></li>
    </ul>
    </div>
    </div>
    <div class="col-sm-6 col-lg-4">
    <div class="single_footer_part">
    <h4>Newsletter</h4>
    <p>Heaven fruitful doesn't over lesser in days. Appear creeping
    </p>
    <div id="mc_embed_signup">
    <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscribe_form relative mail_part">
    <input type="email" name="email" id="newsletter-form-email" placeholder="Email Address" class="placeholder hide-on-focus" onfocus="this.placeholder = ''" onblur="this.placeholder = ' Email Address '">
    <button type="submit" name="submit" id="newsletter-submit" class="email_icon newsletter-submit button-contactForm">subscribe</button>
    <div class="mt-10 info"></div>
    </form>
    </div>
    </div>
    </div>
    </div>
    </div>
    <div class="copyright_part">
    <div class="container">
    <div class="row">
    <div class="col-lg-8">
    <div class="copyright_text">
    <P>
    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com/" target="_blank">Colorlib</a>
    </P>
    </div>
    </div>
    <div class="col-lg-4">
    <div class="footer_icon social_icon">
    <ul class="list-unstyled">
    <li><a href="#" class="single_social_icon"><i class="fab fa-facebook-f"></i></a></li>
    <li><a href="#" class="single_social_icon"><i class="fab fa-twitter"></i></a></li>
    <li><a href="#" class="single_social_icon"><i class="fas fa-globe"></i></a></li>
    <li><a href="#" class="single_social_icon"><i class="fab fa-behance"></i></a></li>
    </ul>
    </div>
    </div>
    </div>
    </div>
    </div>
    </footer>

templates/include/navbar.html
{%load static%}
<header class="main_menu home_menu">
    <div class="container-fluid">
    <div class="row align-items-center">
    <div class="col-lg-12">
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{%url 'home'%}"> <img src="{% static 'img/logo.png'%}" alt="logo"> </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="menu_icon"><i class="fas fa-bars"></i></span>
    </button>
    <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
    <ul class="navbar-nav">
    <li class="nav-item">
    <a class="nav-link" href="{%url 'home'%}">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{%url 'store'%}">Shop</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'category'%}">Category</a>
        </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="{%url 'category'%}" id="navbarDropdown_1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      All Category
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown_1">
        <a class="dropdown-item" href="{%url 'store'%}">All Products</a>
        {% for category in links%}
      <a class="dropdown-item" href="{{category.get_url}}">{{category.category_name}}</a>
    {%endfor%}
      </div>
      </li>
  
   
    <li class="nav-item">
    <a class="nav-link" href="contact.html">Contact</a>
    </li>
   
      <div class="d-flex justify-content-end mb-3 mb-lg-0" >
        {% comment %} style="margin-left: 363px;
      padding-top: 16px;" {% endcomment %}
       {%if user.id is None%}
        <div class="widget-header">
          <small class="title text-muted">Welcome guest!</small>
        <div> 
          <a  href="{% url 'login'%}">Login</a><span class="dark-transp">|</span>
          <a  href="{% url 'register'%}">Register</a>
        </div>
      </div>
      {%else%}
      <div class="widget-header">
        <small class="title text-muted">Welcome {{user.first_name}}!</small>
      <div> 
         <a  href="{%url 'dashboard'%}">Dashboard</a><span class="dark-transp">|</span>
         <a  href="{% url 'logout'%}">Logout</a>
      </div>
    </div>
      {%endif%}
      {% comment %} <div class="nav-item">
        <div class="d-flex align-items-end me-5">
        <a href=" {% url 'wishlist' %}"><img src="{% static 'img/icon/heart.png' %}" alt=""> <span>{{wishlist_count}}</span></a>
        <a href="{% url 'cart' %}"><img src="{% static 'img/icon/cart.png' %}" alt=""> <span>{{cart_count}}</span></a>
        </div>
      </div> {% endcomment %}

    </ul>
      <div class="hearer_icon d-flex">
        <a id="search_1" href="{%static 'javascript:void(0)'%}"><i class="ti-search"></i></a>
        <a href="{% url 'wishlist' %}"><i class="ti-heart"></i></a>
        <div class="dropdown cart">
        <a  href="{% url 'cart' %}" id="navbarDropdown3" role="button" >
        <i class="fas fa-cart-plus"><span>{{cart_count}}</span></i>
        </a>
        
        </div>
        </div>

      


    </div>
    </nav>
    </div>
    </div>
    </div>

    <style>
      .like-btn {
        position: absolute;
        top: 9px;
        left: 15px;
        background: url('twitter-heart.png');
        width: 60px;
        height: 60px;
        background-size: 2900%;
        background-repeat: no-repeat;
      }
      .is-active {
        animation-name: animate;
        animation-duration: .8s;
        animation-iteration-count: 1;
        animation-timing-function: steps(28);
        animation-fill-mode: forwards;
      }
    </style>
    </header>